import Header from '../../../components/Header';
import Footer from '../../../components/Footer';
import LeagueContent from '../../../components/LeagueContent';

export async function generateStaticParams() {
  const leagues = ['英超', '西甲', '意甲', '德甲', '法甲', '欧冠', '欧罗巴', '欧协联', '足总杯', '国王杯', '德国杯', '意大利杯'];
  return leagues.map((name) => ({ name }));
}

interface SeasonData {
  year: string;
  champion: string;
  runnerUp: string;
  topScorer: { name: string; team: string; goals: number };
  avgGoals: number;
  attendance: string;
}

interface LeagueData {
  name: string;
  country: string;
  founded: string;
  teams: number;
  description: string;
  seasons: SeasonData[];
  currentStandings: Array<{ rank: number; team: string; played: number; win: number; draw: number; lose: number; goalsFor: number; goalsAgainst: number; gd: number; points: number }>;
  teamsList: Array<{ name: string; founded: string; stadium: string; capacity: number; coach: string }>;
  rules: string;
  format: string;
}

const leagueData: Record<string, LeagueData> = {
  '英超': {
    name: '英格兰足球超级联赛',
    country: '英格兰',
    founded: '1992年',
    teams: 20,
    description: '英格兰足球超级联赛（简称英超）是英格兰足球总会属下的最高等级职业足球联赛，成立于1992年，是欧洲五大联赛之一。英超以其快节奏、高对抗和全球广泛的影响力而闻名。英超联赛拥有曼联、利物浦、阿森纳、切尔西、曼城等世界顶级豪门俱乐部。',
    format: '20支球队进行主客场双循环赛制，每队38场比赛',
    seasons: [
      { year: '2024-25', champion: '曼城', runnerUp: '阿森纳', topScorer: { name: '哈兰德', team: '曼城', goals: 38 }, avgGoals: 2.81, attendance: '3.8万' },
      { year: '2023-24', champion: '曼城', runnerUp: '阿森纳', topScorer: { name: '哈兰德', team: '曼城', goals: 36 }, avgGoals: 2.78, attendance: '3.7万' },
      { year: '2022-23', champion: '曼城', runnerUp: '阿森纳', topScorer: { name: '哈兰德', team: '曼城', goals: 36 }, avgGoals: 2.80, attendance: '3.6万' },
      { year: '2021-22', champion: '曼城', runnerUp: '利物浦', topScorer: { name: '萨拉赫', team: '利物浦', goals: 23 }, avgGoals: 2.72, attendance: '2.9万' },
      { year: '2020-21', champion: '曼城', runnerUp: '曼联', topScorer: { name: '凯恩', team: '热刺', goals: 23 }, avgGoals: 2.56, attendance: '0.8万' },
      { year: '2019-20', champion: '利物浦', runnerUp: '曼城', topScorer: { name: '瓦尔迪', team: '莱斯特城', goals: 23 }, avgGoals: 2.81, attendance: '2.1万' },
      { year: '2018-19', champion: '曼城', runnerUp: '利物浦', topScorer: { name: '萨拉赫', team: '利物浦', goals: 22 }, avgGoals: 2.75, attendance: '3.8万' },
      { year: '2017-18', champion: '曼城', runnerUp: '曼联', topScorer: { name: '萨拉赫', team: '利物浦', goals: 32 }, avgGoals: 2.80, attendance: '3.8万' },
      { year: '2016-17', champion: '切尔西', runnerUp: '热刺', topScorer: { name: '凯恩', team: '热刺', goals: 29 }, avgGoals: 2.60, attendance: '3.7万' },
      { year: '2015-16', champion: '莱斯特城', runnerUp: '阿森纳', topScorer: { name: '凯恩', team: '热刺', goals: 25 }, avgGoals: 2.53, attendance: '3.6万' },
    ],
    currentStandings: [
      { rank: 1, team: '曼城', played: 38, win: 29, draw: 7, lose: 2, goalsFor: 98, goalsAgainst: 24, gd: 74, points: 94 },
      { rank: 2, team: '阿森纳', played: 38, win: 26, draw: 8, lose: 4, goalsFor: 89, goalsAgainst: 28, gd: 61, points: 86 },
      { rank: 3, team: '利物浦', played: 38, win: 24, draw: 10, lose: 4, goalsFor: 87, goalsAgainst: 34, gd: 53, points: 82 },
      { rank: 4, team: '热刺', played: 38, win: 23, draw: 7, lose: 8, goalsFor: 70, goalsAgainst: 38, gd: 32, points: 76 },
      { rank: 5, team: '曼联', played: 38, win: 21, draw: 10, lose: 7, goalsFor: 62, goalsAgainst: 36, gd: 26, points: 73 },
      { rank: 6, team: '纽卡斯尔', played: 38, win: 19, draw: 10, lose: 9, goalsFor: 65, goalsAgainst: 42, gd: 23, points: 67 },
      { rank: 7, team: '布莱顿', played: 38, win: 18, draw: 8, lose: 12, goalsFor: 60, goalsAgainst: 48, gd: 12, points: 62 },
      { rank: 8, team: '阿斯顿维拉', played: 38, win: 17, draw: 11, lose: 10, goalsFor: 58, goalsAgainst: 50, gd: 8, points: 62 },
      { rank: 9, team: '切尔西', played: 38, win: 16, draw: 10, lose: 12, goalsFor: 55, goalsAgainst: 47, gd: 8, points: 58 },
      { rank: 10, team: '布伦特福德', played: 38, win: 15, draw: 11, lose: 12, goalsFor: 51, goalsAgainst: 53, gd: -2, points: 56 },
      { rank: 11, team: '水晶宫', played: 38, win: 13, draw: 12, lose: 13, goalsFor: 45, goalsAgainst: 50, gd: -5, points: 51 },
      { rank: 12, team: '西汉姆', played: 38, win: 12, draw: 11, lose: 15, goalsFor: 47, goalsAgainst: 55, gd: -8, points: 47 },
      { rank: 13, team: '富勒姆', played: 38, win: 11, draw: 12, lose: 15, goalsFor: 52, goalsAgainst: 60, gd: -8, points: 45 },
      { rank: 14, team: '狼队', played: 38, win: 11, draw: 11, lose: 16, goalsFor: 38, goalsAgainst: 54, gd: -16, points: 44 },
      { rank: 15, team: '伯恩茅斯', played: 38, win: 11, draw: 10, lose: 17, goalsFor: 42, goalsAgainst: 61, gd: -19, points: 43 },
      { rank: 16, team: '埃弗顿', played: 38, win: 10, draw: 12, lose: 16, goalsFor: 38, goalsAgainst: 57, gd: -19, points: 42 },
      { rank: 17, team: '诺丁汉森林', played: 38, win: 9, draw: 11, lose: 18, goalsFor: 46, goalsAgainst: 68, gd: -22, points: 38 },
      { rank: 18, team: '卢顿', played: 38, win: 8, draw: 12, lose: 18, goalsFor: 34, goalsAgainst: 63, gd: -29, points: 36 },
      { rank: 19, team: '伯恩利', played: 38, win: 7, draw: 10, lose: 21, goalsFor: 31, goalsAgainst: 61, gd: -30, points: 31 },
      { rank: 20, team: '谢菲尔德联', played: 38, win: 6, draw: 8, lose: 24, goalsFor: 31, goalsAgainst: 73, gd: -42, points: 26 },
    ],
    teamsList: [
      { name: '曼城', founded: '1880年', stadium: '伊蒂哈德球场', capacity: 53400, coach: '瓜迪奥拉' },
      { name: '阿森纳', founded: '1886年', stadium: '酋长球场', capacity: 60704, coach: '阿尔特塔' },
      { name: '利物浦', founded: '1892年', stadium: '安菲尔德球场', capacity: 61276, coach: '克洛普' },
      { name: '热刺', founded: '1882年', stadium: '托特纳姆热刺球场', capacity: 62062, coach: '波斯特科格鲁' },
      { name: '曼联', founded: '1878年', stadium: '老特拉福德', capacity: 74879, coach: '滕哈格' },
      { name: '切尔西', founded: '1905年', stadium: '斯坦福桥', capacity: 40343, coach: '恩里克' },
      { name: '纽卡斯尔', founded: '1892年', stadium: '圣詹姆斯公园', capacity: 52387, coach: '埃迪·豪' },
      { name: '阿斯顿维拉', founded: '1874年', stadium: '维拉公园', capacity: 42657, coach: '埃梅里' },
    ],
    rules: '英超联赛共有20支球队，每支球队需进行38场比赛（主客场各19场）。赛季结束后，积分榜前三名获得欧冠参赛资格，第四名获得欧冠附加赛资格，第五名获得欧联杯资格，第六名获得欧协联资格。积分榜最后三名降级至英冠联赛。',
  },
  '西甲': {
    name: '西班牙足球甲级联赛',
    country: '西班牙',
    founded: '1929年',
    teams: 20,
    description: '西班牙足球甲级联赛（简称西甲）是西班牙最高等级的职业足球联赛，成立于1929年。西甲以其技术流打法和巴塞罗那、皇家马德里等豪门俱乐部而闻名于世。西甲联赛培养了梅西、C罗等众多世界级球星。',
    format: '20支球队进行主客场双循环赛制，每队38场比赛',
    seasons: [
      { year: '2024-25', champion: '皇家马德里', runnerUp: '巴塞罗那', topScorer: { name: '维尼修斯', team: '皇家马德里', goals: 29 }, avgGoals: 2.65, attendance: '2.8万' },
      { year: '2023-24', champion: '皇家马德里', runnerUp: '巴塞罗那', topScorer: { name: '莱万多夫斯基', team: '巴塞罗那', goals: 24 }, avgGoals: 2.58, attendance: '2.7万' },
      { year: '2022-23', champion: '巴塞罗那', runnerUp: '皇家马德里', topScorer: { name: '本泽马', team: '皇家马德里', goals: 24 }, avgGoals: 2.55, attendance: '2.6万' },
      { year: '2021-22', champion: '皇家马德里', runnerUp: '巴塞罗那', topScorer: { name: '本泽马', team: '皇家马德里', goals: 27 }, avgGoals: 2.45, attendance: '2.1万' },
      { year: '2020-21', champion: '马德里竞技', runnerUp: '皇家马德里', topScorer: { name: '梅西', team: '巴塞罗那', goals: 30 }, avgGoals: 2.35, attendance: '0.7万' },
      { year: '2019-20', champion: '皇家马德里', runnerUp: '巴塞罗那', topScorer: { name: '梅西', team: '巴塞罗那', goals: 25 }, avgGoals: 2.42, attendance: '1.5万' },
      { year: '2018-19', champion: '巴塞罗那', runnerUp: '马德里竞技', topScorer: { name: '梅西', team: '巴塞罗那', goals: 36 }, avgGoals: 2.60, attendance: '2.8万' },
      { year: '2017-18', champion: '巴塞罗那', runnerUp: '皇家马德里', topScorer: { name: '梅西', team: '巴塞罗那', goals: 34 }, avgGoals: 2.62, attendance: '2.8万' },
      { year: '2016-17', champion: '皇家马德里', runnerUp: '巴塞罗那', topScorer: { name: '梅西', team: '巴塞罗那', goals: 37 }, avgGoals: 2.68, attendance: '2.7万' },
      { year: '2015-16', champion: '巴塞罗那', runnerUp: '皇家马德里', topScorer: { name: '苏亚雷斯', team: '巴塞罗那', goals: 40 }, avgGoals: 2.82, attendance: '2.7万' },
    ],
    currentStandings: [
      { rank: 1, team: '皇家马德里', played: 38, win: 28, draw: 7, lose: 3, goalsFor: 82, goalsAgainst: 26, gd: 56, points: 91 },
      { rank: 2, team: '巴塞罗那', played: 38, win: 27, draw: 6, lose: 5, goalsFor: 85, goalsAgainst: 29, gd: 56, points: 87 },
      { rank: 3, team: '马德里竞技', played: 38, win: 23, draw: 9, lose: 6, goalsFor: 62, goalsAgainst: 25, gd: 37, points: 78 },
      { rank: 4, team: '比利亚雷亚尔', played: 38, win: 19, draw: 10, lose: 9, goalsFor: 58, goalsAgainst: 36, gd: 22, points: 67 },
      { rank: 5, team: '塞维利亚', played: 38, win: 18, draw: 9, lose: 11, goalsFor: 52, goalsAgainst: 40, gd: 12, points: 63 },
      { rank: 6, team: '皇家社会', played: 38, win: 17, draw: 10, lose: 11, goalsFor: 48, goalsAgainst: 40, gd: 8, points: 61 },
      { rank: 7, team: '贝蒂斯', played: 38, win: 16, draw: 11, lose: 11, goalsFor: 50, goalsAgainst: 45, gd: 5, points: 59 },
      { rank: 8, team: '赫罗纳', played: 38, win: 15, draw: 12, lose: 11, goalsFor: 52, goalsAgainst: 47, gd: 5, points: 57 },
      { rank: 9, team: '毕尔巴鄂竞技', played: 38, win: 14, draw: 12, lose: 12, goalsFor: 43, goalsAgainst: 38, gd: 5, points: 54 },
      { rank: 10, team: '奥萨苏纳', played: 38, win: 13, draw: 13, lose: 12, goalsFor: 42, goalsAgainst: 45, gd: -3, points: 52 },
      { rank: 11, team: '瓦伦西亚', played: 38, win: 12, draw: 14, lose: 12, goalsFor: 45, goalsAgainst: 46, gd: -1, points: 50 },
      { rank: 12, team: '塞尔塔', played: 38, win: 12, draw: 12, lose: 14, goalsFor: 48, goalsAgainst: 55, gd: -7, points: 48 },
      { rank: 13, team: '阿拉维斯', played: 38, win: 11, draw: 14, lose: 13, goalsFor: 40, goalsAgainst: 49, gd: -9, points: 47 },
      { rank: 14, team: '马洛卡', played: 38, win: 11, draw: 12, lose: 15, goalsFor: 37, goalsAgainst: 48, gd: -11, points: 45 },
      { rank: 15, team: '赫塔菲', played: 38, win: 10, draw: 14, lose: 14, goalsFor: 34, goalsAgainst: 46, gd: -12, points: 44 },
      { rank: 16, team: '格拉纳达', played: 38, win: 10, draw: 12, lose: 16, goalsFor: 40, goalsAgainst: 55, gd: -15, points: 42 },
      { rank: 17, team: '巴列卡诺', played: 38, win: 10, draw: 11, lose: 17, goalsFor: 41, goalsAgainst: 58, gd: -17, points: 41 },
      { rank: 18, team: '加的斯', played: 38, win: 8, draw: 14, lose: 16, goalsFor: 32, goalsAgainst: 50, gd: -18, points: 38 },
      { rank: 19, team: '阿尔梅里亚', played: 38, win: 7, draw: 13, lose: 18, goalsFor: 35, goalsAgainst: 61, gd: -26, points: 34 },
      { rank: 20, team: '拉斯帕尔马斯', played: 38, win: 6, draw: 12, lose: 20, goalsFor: 30, goalsAgainst: 62, gd: -32, points: 30 },
    ],
    teamsList: [
      { name: '皇家马德里', founded: '1902年', stadium: '伯纳乌球场', capacity: 81044, coach: '安切洛蒂' },
      { name: '巴塞罗那', founded: '1899年', stadium: '诺坎普', capacity: 99354, coach: '哈维' },
      { name: '马德里竞技', founded: '1903年', stadium: '万达大都会', capacity: 68456, coach: '西蒙尼' },
      { name: '塞维利亚', founded: '1905年', stadium: '拉蒙·桑切斯', capacity: 42714, coach: '门迪利巴' },
      { name: '比利亚雷亚尔', founded: '1923年', stadium: '陶瓷球场', capacity: 23500, coach: '埃梅里' },
      { name: '皇家社会', founded: '1909年', stadium: '阿诺埃塔球场', capacity: 39500, coach: '伊马诺尔' },
    ],
    rules: '西甲联赛共有20支球队，每支球队需进行38场比赛（主客场各19场）。赛季结束后，积分榜前三名获得欧冠参赛资格，第四名获得欧冠附加赛资格，第五名获得欧联杯资格，第六名获得欧协联资格。积分榜最后三名降级至西乙联赛。',
  },
  '意甲': {
    name: '意大利足球甲级联赛',
    country: '意大利',
    founded: '1898年',
    teams: 20,
    description: '意大利足球甲级联赛（简称意甲）是意大利最高等级的职业足球联赛，成立于1898年。意甲以其防守战术和AC米兰、国际米兰、尤文图斯等豪门俱乐部而闻名。意甲联赛曾培养了巴乔、马拉多纳、罗纳尔多等众多传奇球星。',
    format: '20支球队进行主客场双循环赛制，每队38场比赛',
    seasons: [
      { year: '2024-25', champion: '国际米兰', runnerUp: 'AC米兰', topScorer: { name: '劳塔罗', team: '国际米兰', goals: 28 }, avgGoals: 2.45, attendance: '2.5万' },
      { year: '2023-24', champion: '国际米兰', runnerUp: '尤文图斯', topScorer: { name: '劳塔罗', team: '国际米兰', goals: 26 }, avgGoals: 2.42, attendance: '2.4万' },
      { year: '2022-23', champion: '那不勒斯', runnerUp: '拉齐奥', topScorer: { name: '奥斯梅恩', team: '那不勒斯', goals: 26 }, avgGoals: 2.38, attendance: '2.3万' },
      { year: '2021-22', champion: 'AC米兰', runnerUp: '国际米兰', topScorer: { name: '因莫比莱', team: '拉齐奥', goals: 27 }, avgGoals: 2.35, attendance: '1.9万' },
      { year: '2020-21', champion: '国际米兰', runnerUp: 'AC米兰', topScorer: { name: 'C罗', team: '尤文图斯', goals: 29 }, avgGoals: 2.28, attendance: '0.5万' },
      { year: '2019-20', champion: '尤文图斯', runnerUp: '国际米兰', topScorer: { name: '因莫比莱', team: '拉齐奥', goals: 36 }, avgGoals: 2.40, attendance: '1.1万' },
      { year: '2018-19', champion: '尤文图斯', runnerUp: '那不勒斯', topScorer: { name: '夸利亚雷拉', team: '桑普多利亚', goals: 26 }, avgGoals: 2.35, attendance: '2.7万' },
      { year: '2017-18', champion: '尤文图斯', runnerUp: '那不勒斯', topScorer: { name: '伊卡尔迪', team: '国际米兰', goals: 29 }, avgGoals: 2.42, attendance: '2.7万' },
      { year: '2016-17', champion: '尤文图斯', runnerUp: '罗马', topScorer: { name: '迪巴拉', team: '尤文图斯', goals: 11 }, avgGoals: 2.28, attendance: '2.6万' },
      { year: '2015-16', champion: '尤文图斯', runnerUp: '那不勒斯', topScorer: { name: '伊瓜因', team: '那不勒斯', goals: 36 }, avgGoals: 2.40, attendance: '2.6万' },
    ],
    currentStandings: [
      { rank: 1, team: '国际米兰', played: 38, win: 28, draw: 7, lose: 3, goalsFor: 78, goalsAgainst: 26, gd: 52, points: 91 },
      { rank: 2, team: 'AC米兰', played: 38, win: 25, draw: 8, lose: 5, goalsFor: 74, goalsAgainst: 33, gd: 41, points: 83 },
      { rank: 3, team: '尤文图斯', played: 38, win: 24, draw: 9, lose: 5, goalsFor: 67, goalsAgainst: 28, gd: 39, points: 81 },
      { rank: 4, team: '那不勒斯', played: 38, win: 22, draw: 10, lose: 6, goalsFor: 70, goalsAgainst: 31, gd: 39, points: 76 },
      { rank: 5, team: '拉齐奥', played: 38, win: 20, draw: 10, lose: 8, goalsFor: 62, goalsAgainst: 38, gd: 24, points: 70 },
      { rank: 6, team: '罗马', played: 38, win: 18, draw: 11, lose: 9, goalsFor: 58, goalsAgainst: 40, gd: 18, points: 65 },
      { rank: 7, team: '亚特兰大', played: 38, win: 17, draw: 10, lose: 11, goalsFor: 64, goalsAgainst: 47, gd: 17, points: 61 },
      { rank: 8, team: '佛罗伦萨', played: 38, win: 15, draw: 13, lose: 10, goalsFor: 51, goalsAgainst: 42, gd: 9, points: 58 },
      { rank: 9, team: '博洛尼亚', played: 38, win: 15, draw: 12, lose: 11, goalsFor: 48, goalsAgainst: 44, gd: 4, points: 57 },
      { rank: 10, team: '都灵', played: 38, win: 13, draw: 12, lose: 13, goalsFor: 41, goalsAgainst: 47, gd: -6, points: 51 },
      { rank: 11, team: '乌迪内斯', played: 38, win: 12, draw: 14, lose: 12, goalsFor: 43, goalsAgainst: 45, gd: -2, points: 50 },
      { rank: 12, team: '萨索洛', played: 38, win: 12, draw: 11, lose: 15, goalsFor: 45, goalsAgainst: 55, gd: -10, points: 47 },
      { rank: 13, team: '热那亚', played: 38, win: 11, draw: 13, lose: 14, goalsFor: 39, goalsAgainst: 50, gd: -11, points: 46 },
      { rank: 14, team: '维罗纳', played: 38, win: 10, draw: 14, lose: 14, goalsFor: 36, goalsAgainst: 46, gd: -10, points: 44 },
      { rank: 15, team: '莱切', played: 38, win: 10, draw: 12, lose: 16, goalsFor: 42, goalsAgainst: 56, gd: -14, points: 42 },
      { rank: 16, team: '蒙扎', played: 38, win: 9, draw: 14, lose: 15, goalsFor: 38, goalsAgainst: 52, gd: -14, points: 41 },
      { rank: 17, team: '卡利亚里', played: 38, win: 9, draw: 12, lose: 17, goalsFor: 35, goalsAgainst: 54, gd: -19, points: 39 },
      { rank: 18, team: '恩波利', played: 38, win: 7, draw: 13, lose: 18, goalsFor: 32, goalsAgainst: 58, gd: -26, points: 34 },
      { rank: 19, team: '弗罗西诺内', played: 38, win: 6, draw: 10, lose: 22, goalsFor: 30, goalsAgainst: 66, gd: -36, points: 28 },
      { rank: 20, team: '萨勒尼塔纳', played: 38, win: 5, draw: 9, lose: 24, goalsFor: 25, goalsAgainst: 70, gd: -45, points: 24 },
    ],
    teamsList: [
      { name: '国际米兰', founded: '1908年', stadium: '梅阿查球场', capacity: 75817, coach: '因扎吉' },
      { name: 'AC米兰', founded: '1899年', stadium: '圣西罗球场', capacity: 75817, coach: '丰塞卡' },
      { name: '尤文图斯', founded: '1897年', stadium: '安联球场', capacity: 41507, coach: '阿莱格里' },
      { name: '那不勒斯', founded: '1926年', stadium: '迭戈·阿曼多·马拉多纳球场', capacity: 54726, coach: '鲁迪·加西亚' },
      { name: '罗马', founded: '1927年', stadium: '奥林匹克球场', capacity: 70634, coach: '穆里尼奥' },
      { name: '拉齐奥', founded: '1900年', stadium: '奥林匹克球场', capacity: 70634, coach: '萨里' },
    ],
    rules: '意甲联赛共有20支球队，每支球队需进行38场比赛（主客场各19场）。赛季结束后，积分榜前三名获得欧冠参赛资格，第四名获得欧冠附加赛资格，第五名获得欧联杯资格，第六名获得欧协联资格。积分榜最后三名降级至意乙联赛。',
  },
  '德甲': {
    name: '德国足球甲级联赛',
    country: '德国',
    founded: '1963年',
    teams: 18,
    description: '德国足球甲级联赛（简称德甲）是德国最高等级的职业足球联赛，成立于1963年。德甲以其高效的组织和拜仁慕尼黑等豪门俱乐部而闻名。德甲联赛培养了贝肯鲍尔、盖德·穆勒等众多传奇球星。',
    format: '18支球队进行主客场双循环赛制，每队34场比赛',
    seasons: [
      { year: '2024-25', champion: '勒沃库森', runnerUp: '拜仁慕尼黑', topScorer: { name: '维尔茨', team: '勒沃库森', goals: 25 }, avgGoals: 2.85, attendance: '4.2万' },
      { year: '2023-24', champion: '勒沃库森', runnerUp: '拜仁慕尼黑', topScorer: { name: '希克', team: '勒沃库森', goals: 24 }, avgGoals: 2.82, attendance: '4.1万' },
      { year: '2022-23', champion: '拜仁慕尼黑', runnerUp: '多特蒙德', topScorer: { name: '哈兰德', team: '多特蒙德', goals: 27 }, avgGoals: 2.80, attendance: '4.0万' },
      { year: '2021-22', champion: '拜仁慕尼黑', runnerUp: '多特蒙德', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 35 }, avgGoals: 2.92, attendance: '3.0万' },
      { year: '2020-21', champion: '拜仁慕尼黑', runnerUp: '莱比锡', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 41 }, avgGoals: 2.75, attendance: '0.5万' },
      { year: '2019-20', champion: '拜仁慕尼黑', runnerUp: '多特蒙德', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 34 }, avgGoals: 3.10, attendance: '1.8万' },
      { year: '2018-19', champion: '拜仁慕尼黑', runnerUp: '多特蒙德', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 22 }, avgGoals: 3.02, attendance: '4.4万' },
      { year: '2017-18', champion: '拜仁慕尼黑', runnerUp: '沙尔克04', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 29 }, avgGoals: 3.05, attendance: '4.4万' },
      { year: '2016-17', champion: '拜仁慕尼黑', runnerUp: 'RB莱比锡', topScorer: { name: '奥巴梅扬', team: '多特蒙德', goals: 31 }, avgGoals: 2.88, attendance: '4.3万' },
      { year: '2015-16', champion: '拜仁慕尼黑', runnerUp: '多特蒙德', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 30 }, avgGoals: 2.85, attendance: '4.3万' },
    ],
    currentStandings: [
      { rank: 1, team: '勒沃库森', played: 34, win: 29, draw: 4, lose: 1, goalsFor: 89, goalsAgainst: 24, gd: 65, points: 91 },
      { rank: 2, team: '拜仁慕尼黑', played: 34, win: 26, draw: 5, lose: 3, goalsFor: 81, goalsAgainst: 23, gd: 58, points: 83 },
      { rank: 3, team: '多特蒙德', played: 34, win: 22, draw: 8, lose: 4, goalsFor: 71, goalsAgainst: 32, gd: 39, points: 74 },
      { rank: 4, team: 'RB莱比锡', played: 34, win: 20, draw: 9, lose: 5, goalsFor: 66, goalsAgainst: 31, gd: 35, points: 69 },
      { rank: 5, team: '法兰克福', played: 34, win: 16, draw: 10, lose: 8, goalsFor: 58, goalsAgainst: 38, gd: 20, points: 58 },
      { rank: 6, team: '沃尔夫斯堡', played: 34, win: 15, draw: 9, lose: 10, goalsFor: 51, goalsAgainst: 43, gd: 8, points: 54 },
      { rank: 7, team: '科隆', played: 34, win: 14, draw: 11, lose: 9, goalsFor: 52, goalsAgainst: 42, gd: 10, points: 53 },
      { rank: 8, team: '霍芬海姆', played: 34, win: 13, draw: 11, lose: 10, goalsFor: 53, goalsAgainst: 46, gd: 7, points: 50 },
      { rank: 9, team: '柏林联合', played: 34, win: 12, draw: 12, lose: 10, goalsFor: 45, goalsAgainst: 40, gd: 5, points: 48 },
      { rank: 10, team: '门兴', played: 34, win: 11, draw: 13, lose: 10, goalsFor: 47, goalsAgainst: 44, gd: 3, points: 46 },
      { rank: 11, team: '弗赖堡', played: 34, win: 10, draw: 14, lose: 10, goalsFor: 40, goalsAgainst: 42, gd: -2, points: 44 },
      { rank: 12, team: '美因茨', played: 34, win: 10, draw: 12, lose: 12, goalsFor: 42, goalsAgainst: 50, gd: -8, points: 42 },
      { rank: 13, team: '奥格斯堡', played: 34, win: 9, draw: 12, lose: 13, goalsFor: 36, goalsAgainst: 50, gd: -14, points: 39 },
      { rank: 14, team: '波鸿', played: 34, win: 8, draw: 12, lose: 14, goalsFor: 35, goalsAgainst: 52, gd: -17, points: 36 },
      { rank: 15, team: '达姆施塔特', played: 34, win: 7, draw: 13, lose: 14, goalsFor: 32, goalsAgainst: 51, gd: -19, points: 34 },
      { rank: 16, team: '海登海姆', played: 34, win: 7, draw: 11, lose: 16, goalsFor: 30, goalsAgainst: 54, gd: -24, points: 32 },
      { rank: 17, team: '斯图加特', played: 34, win: 6, draw: 13, lose: 15, goalsFor: 35, goalsAgainst: 56, gd: -21, points: 31 },
      { rank: 18, team: '云达不莱梅', played: 34, win: 5, draw: 10, lose: 19, goalsFor: 30, goalsAgainst: 65, gd: -35, points: 25 },
    ],
    teamsList: [
      { name: '拜仁慕尼黑', founded: '1900年', stadium: '安联球场', capacity: 75024, coach: '图赫尔' },
      { name: '多特蒙德', founded: '1909年', stadium: '信号公园球场', capacity: 81365, coach: '泰尔齐奇' },
      { name: '勒沃库森', founded: '1904年', stadium: '拜耳竞技场', capacity: 30210, coach: '哈维·阿隆索' },
      { name: 'RB莱比锡', founded: '2009年', stadium: '红牛竞技场', capacity: 42558, coach: '罗斯' },
      { name: '沃尔夫斯堡', founded: '1945年', stadium: '大众汽车球场', capacity: 30000, coach: '科瓦奇' },
      { name: '门兴格拉德巴赫', founded: '1900年', stadium: '普鲁士公园球场', capacity: 54057, coach: '法尔克' },
    ],
    rules: '德甲联赛共有18支球队，每支球队需进行34场比赛（主客场各17场）。赛季结束后，积分榜前三名获得欧冠参赛资格，第四名获得欧冠附加赛资格，第五名获得欧联杯资格，第六名获得欧协联资格。积分榜最后两名降级至德乙联赛，第16名与德乙第3名进行升降级附加赛。',
  },
  '法甲': {
    name: '法国足球甲级联赛',
    country: '法国',
    founded: '1932年',
    teams: 20,
    description: '法国足球甲级联赛（简称法甲）是法国最高等级的职业足球联赛，成立于1932年。法甲以其技术流打法和巴黎圣日耳曼等豪门俱乐部而闻名。法甲联赛培养了普拉蒂尼、齐达内等众多传奇球星。',
    format: '20支球队进行主客场双循环赛制，每队38场比赛',
    seasons: [
      { year: '2024-25', champion: '巴黎圣日耳曼', runnerUp: '里昂', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 32 }, avgGoals: 2.55, attendance: '2.5万' },
      { year: '2023-24', champion: '巴黎圣日耳曼', runnerUp: '里尔', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 31 }, avgGoals: 2.52, attendance: '2.4万' },
      { year: '2022-23', champion: '巴黎圣日耳曼', runnerUp: '朗斯', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 29 }, avgGoals: 2.48, attendance: '2.3万' },
      { year: '2021-22', champion: '巴黎圣日耳曼', runnerUp: '马赛', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 28 }, avgGoals: 2.45, attendance: '2.0万' },
      { year: '2020-21', champion: '里尔', runnerUp: '巴黎圣日耳曼', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 27 }, avgGoals: 2.35, attendance: '0.8万' },
      { year: '2019-20', champion: '巴黎圣日耳曼', runnerUp: '马赛', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 18 }, avgGoals: 2.52, attendance: '1.2万' },
      { year: '2018-19', champion: '巴黎圣日耳曼', runnerUp: '里昂', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 33 }, avgGoals: 2.68, attendance: '2.8万' },
      { year: '2017-18', champion: '巴黎圣日耳曼', runnerUp: '摩纳哥', topScorer: { name: '姆巴佩', team: '摩纳哥', goals: 15 }, avgGoals: 2.75, attendance: '2.7万' },
      { year: '2016-17', champion: '摩纳哥', runnerUp: '巴黎圣日耳曼', topScorer: { name: '姆巴佩', team: '摩纳哥', goals: 15 }, avgGoals: 2.82, attendance: '2.6万' },
      { year: '2015-16', champion: '巴黎圣日耳曼', runnerUp: '里昂', topScorer: { name: '卡瓦尼', team: '巴黎圣日耳曼', goals: 35 }, avgGoals: 2.65, attendance: '2.5万' },
    ],
    currentStandings: [
      { rank: 1, team: '巴黎圣日耳曼', played: 38, win: 29, draw: 6, lose: 3, goalsFor: 95, goalsAgainst: 29, gd: 66, points: 93 },
      { rank: 2, team: '里昂', played: 38, win: 24, draw: 8, lose: 6, goalsFor: 72, goalsAgainst: 34, gd: 38, points: 80 },
      { rank: 3, team: '里尔', played: 38, win: 22, draw: 10, lose: 6, goalsFor: 60, goalsAgainst: 32, gd: 28, points: 76 },
      { rank: 4, team: '马赛', played: 38, win: 21, draw: 9, lose: 8, goalsFor: 63, goalsAgainst: 38, gd: 25, points: 72 },
      { rank: 5, team: '朗斯', played: 38, win: 20, draw: 10, lose: 8, goalsFor: 58, goalsAgainst: 36, gd: 22, points: 70 },
      { rank: 6, team: '摩纳哥', played: 38, win: 18, draw: 11, lose: 9, goalsFor: 55, goalsAgainst: 39, gd: 16, points: 65 },
      { rank: 7, team: '雷恩', played: 38, win: 17, draw: 10, lose: 11, goalsFor: 52, goalsAgainst: 44, gd: 8, points: 61 },
      { rank: 8, team: '尼斯', played: 38, win: 15, draw: 12, lose: 11, goalsFor: 50, goalsAgainst: 45, gd: 5, points: 57 },
      { rank: 9, team: '布雷斯特', played: 38, win: 14, draw: 13, lose: 11, goalsFor: 47, goalsAgainst: 44, gd: 3, points: 55 },
      { rank: 10, team: '洛里昂', played: 38, win: 13, draw: 13, lose: 12, goalsFor: 46, goalsAgainst: 50, gd: -4, points: 52 },
      { rank: 11, team: '图卢兹', played: 38, win: 12, draw: 13, lose: 13, goalsFor: 45, goalsAgainst: 52, gd: -7, points: 49 },
      { rank: 12, team: '蒙彼利埃', played: 38, win: 11, draw: 14, lose: 13, goalsFor: 40, goalsAgainst: 47, gd: -7, points: 47 },
      { rank: 13, team: '兰斯', played: 38, win: 11, draw: 13, lose: 14, goalsFor: 38, goalsAgainst: 48, gd: -10, points: 46 },
      { rank: 14, team: '斯特拉斯堡', played: 38, win: 10, draw: 14, lose: 14, goalsFor: 42, goalsAgainst: 51, gd: -9, points: 44 },
      { rank: 15, team: '梅斯', played: 38, win: 10, draw: 12, lose: 16, goalsFor: 35, goalsAgainst: 50, gd: -15, points: 42 },
      { rank: 16, team: '克莱蒙', played: 38, win: 9, draw: 14, lose: 15, goalsFor: 36, goalsAgainst: 52, gd: -16, points: 41 },
      { rank: 17, team: '南特', played: 38, win: 9, draw: 12, lose: 17, goalsFor: 33, goalsAgainst: 55, gd: -22, points: 39 },
      { rank: 18, team: '昂热', played: 38, win: 7, draw: 14, lose: 17, goalsFor: 32, goalsAgainst: 54, gd: -22, points: 35 },
      { rank: 19, team: '第戎', played: 38, win: 6, draw: 12, lose: 20, goalsFor: 28, goalsAgainst: 62, gd: -34, points: 30 },
      { rank: 20, team: '欧塞尔', played: 38, win: 5, draw: 10, lose: 23, goalsFor: 26, goalsAgainst: 68, gd: -42, points: 25 },
    ],
    teamsList: [
      { name: '巴黎圣日耳曼', founded: '1970年', stadium: '王子公园球场', capacity: 48583, coach: '恩里克' },
      { name: '里昂', founded: '1950年', stadium: '奥林匹克球场', capacity: 59186, coach: '法夫尔' },
      { name: '马赛', founded: '1899年', stadium: '韦洛德罗姆球场', capacity: 67394, coach: '图多尔' },
      { name: '里尔', founded: '1944年', stadium: '皮埃尔·莫鲁瓦球场', capacity: 50186, coach: '丰塞卡' },
      { name: '摩纳哥', founded: '1924年', stadium: '路易二世球场', capacity: 18523, coach: '克莱门特' },
      { name: '雷恩', founded: '1901年', stadium: '罗阿宗公园球场', capacity: 29778, coach: '热内西奥' },
    ],
    rules: '法甲联赛共有20支球队，每支球队需进行38场比赛（主客场各19场）。赛季结束后，积分榜前三名获得欧冠参赛资格，第四名获得欧冠附加赛资格，第五名获得欧联杯资格，第六名获得欧协联资格。积分榜最后两名直接降级，第18名与法乙第三名进行升降级附加赛。',
  },
  '欧冠': {
    name: '欧洲冠军联赛',
    country: '欧洲',
    founded: '1955年',
    teams: 32,
    description: '欧洲冠军联赛（简称欧冠）是欧洲足球协会联盟主办的年度足球俱乐部赛事，成立于1955年，是欧洲俱乐部足球最高荣誉和最具影响力的赛事。欧冠联赛汇聚了欧洲各大联赛的顶级豪门。',
    format: '32支球队进入小组赛，8个小组每组4队进行双循环，小组前两名晋级淘汰赛',
    seasons: [
      { year: '2024-25', champion: '曼城', runnerUp: '皇家马德里', topScorer: { name: '哈兰德', team: '曼城', goals: 14 }, avgGoals: 2.75, attendance: '5.5万' },
      { year: '2023-24', champion: '皇家马德里', runnerUp: '多特蒙德', topScorer: { name: '姆巴佩', team: '巴黎圣日耳曼', goals: 12 }, avgGoals: 2.72, attendance: '5.4万' },
      { year: '2022-23', champion: '曼城', runnerUp: '国际米兰', topScorer: { name: '哈兰德', team: '曼城', goals: 12 }, avgGoals: 2.68, attendance: '5.3万' },
      { year: '2021-22', champion: '皇家马德里', runnerUp: '利物浦', topScorer: { name: '本泽马', team: '皇家马德里', goals: 15 }, avgGoals: 2.65, attendance: '4.5万' },
      { year: '2020-21', champion: '切尔西', runnerUp: '曼城', topScorer: { name: '哈兰德', team: '多特蒙德', goals: 10 }, avgGoals: 2.58, attendance: '1.8万' },
      { year: '2019-20', champion: '拜仁慕尼黑', runnerUp: '巴黎圣日耳曼', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 15 }, avgGoals: 2.70, attendance: '0.5万' },
      { year: '2018-19', champion: '利物浦', runnerUp: '托特纳姆热刺', topScorer: { name: '梅西', team: '巴塞罗那', goals: 12 }, avgGoals: 2.75, attendance: '5.8万' },
      { year: '2017-18', champion: '皇家马德里', runnerUp: '利物浦', topScorer: { name: 'C罗', team: '皇家马德里', goals: 15 }, avgGoals: 2.82, attendance: '5.7万' },
      { year: '2016-17', champion: '皇家马德里', runnerUp: '尤文图斯', topScorer: { name: 'C罗', team: '皇家马德里', goals: 12 }, avgGoals: 2.78, attendance: '5.6万' },
      { year: '2015-16', champion: '皇家马德里', runnerUp: '马德里竞技', topScorer: { name: 'C罗', team: '皇家马德里', goals: 16 }, avgGoals: 2.85, attendance: '5.5万' },
    ],
    currentStandings: [],
    teamsList: [
      { name: '曼城', founded: '1880年', stadium: '伊蒂哈德球场', capacity: 53400, coach: '瓜迪奥拉' },
      { name: '皇家马德里', founded: '1902年', stadium: '伯纳乌球场', capacity: 81044, coach: '安切洛蒂' },
      { name: '拜仁慕尼黑', founded: '1900年', stadium: '安联球场', capacity: 75024, coach: '图赫尔' },
      { name: '利物浦', founded: '1892年', stadium: '安菲尔德球场', capacity: 61276, coach: '克洛普' },
      { name: '巴塞罗那', founded: '1899年', stadium: '诺坎普', capacity: 99354, coach: '哈维' },
      { name: '尤文图斯', founded: '1897年', stadium: '安联球场', capacity: 41507, coach: '阿莱格里' },
    ],
    rules: '欧冠联赛共有32支球队进入小组赛阶段，分为8个小组，每组4支球队进行双循环比赛。小组前两名晋级淘汰赛阶段，淘汰赛采用主客场两回合制。决赛为单场决胜，在中立场地进行。',
  },
  '欧罗巴': {
    name: '欧足联欧洲联赛',
    country: '欧洲',
    founded: '1971年',
    teams: 32,
    description: '欧足联欧洲联赛（简称欧联杯）是欧洲足球协会联盟主办的仅次于欧冠的俱乐部赛事，成立于1971年，为欧洲各大联赛的中游球队提供了欧洲赛场的机会。',
    format: '32支球队进入小组赛，8个小组每组4队进行双循环，小组前两名晋级淘汰赛',
    seasons: [
      { year: '2024-25', champion: '阿斯顿维拉', runnerUp: '勒沃库森', topScorer: { name: '沃特金斯', team: '阿斯顿维拉', goals: 11 }, avgGoals: 2.55, attendance: '3.5万' },
      { year: '2023-24', champion: '塞维利亚', runnerUp: '罗马', topScorer: { name: '拉卡泽特', team: '里昂', goals: 9 }, avgGoals: 2.48, attendance: '3.4万' },
      { year: '2022-23', champion: '塞维利亚', runnerUp: '罗马', topScorer: { name: '奥尔莫', team: '莱比锡', goals: 8 }, avgGoals: 2.42, attendance: '3.3万' },
      { year: '2021-22', champion: '法兰克福', runnerUp: '流浪者', topScorer: { name: 'Aribo', team: '流浪者', goals: 7 }, avgGoals: 2.38, attendance: '2.8万' },
      { year: '2020-21', champion: '比利亚雷亚尔', runnerUp: '曼联', topScorer: { name: 'Gerard Moreno', team: '比利亚雷亚尔', goals: 7 }, avgGoals: 2.35, attendance: '1.2万' },
      { year: '2019-20', champion: '塞维利亚', runnerUp: '国际米兰', topScorer: { name: 'Lukaku', team: '国际米兰', goals: 8 }, avgGoals: 2.45, attendance: '0.8万' },
      { year: '2018-19', champion: '切尔西', runnerUp: '阿森纳', topScorer: { name: 'Aubameyang', team: '阿森纳', goals: 8 }, avgGoals: 2.52, attendance: '3.8万' },
      { year: '2017-18', champion: '马竞', runnerUp: '马赛', topScorer: { name: 'Griezmann', team: '马竞', goals: 8 }, avgGoals: 2.48, attendance: '3.7万' },
      { year: '2016-17', champion: '曼联', runnerUp: '阿贾克斯', topScorer: { name: 'Mkhitaryan', team: '曼联', goals: 6 }, avgGoals: 2.42, attendance: '3.6万' },
      { year: '2015-16', champion: '塞维利亚', runnerUp: '利物浦', topScorer: { name: 'Bacca', team: '塞维利亚', goals: 8 }, avgGoals: 2.38, attendance: '3.5万' },
    ],
    currentStandings: [],
    teamsList: [
      { name: '塞维利亚', founded: '1905年', stadium: '拉蒙·桑切斯', capacity: 42714, coach: '门迪利巴' },
      { name: '罗马', founded: '1927年', stadium: '奥林匹克球场', capacity: 70634, coach: '穆里尼奥' },
      { name: '比利亚雷亚尔', founded: '1923年', stadium: '陶瓷球场', capacity: 23500, coach: '埃梅里' },
      { name: '法兰克福', founded: '1899年', stadium: '商业银行竞技场', capacity: 51500, coach: '格拉斯纳' },
    ],
    rules: '欧联杯联赛共有32支球队进入小组赛阶段，分为8个小组，每组4支球队进行双循环比赛。小组前两名晋级淘汰赛阶段，淘汰赛采用主客场两回合制。决赛为单场决胜，在中立场地进行。',
  },
  '欧协联': {
    name: '欧足联欧洲协会联赛',
    country: '欧洲',
    founded: '2021年',
    teams: 32,
    description: '欧足联欧洲协会联赛（简称欧协联）是欧洲足球协会联盟主办的第三级欧洲俱乐部赛事，成立于2021年，为更多欧洲俱乐部提供了参加欧洲赛事的机会。欧协联冠军可获得下赛季欧联杯资格。',
    format: '32支球队进入小组赛，8个小组每组4队进行双循环，小组第一和最佳小组第二晋级淘汰赛',
    seasons: [
      { year: '2024-25', champion: '西汉姆联', runnerUp: '佛罗伦萨', topScorer: { name: '安东尼奥', team: '西汉姆联', goals: 10 }, avgGoals: 2.42, attendance: '2.8万' },
      { year: '2023-24', champion: '阿斯顿维拉', runnerUp: '里尔', topScorer: { name: '沃特金斯', team: '阿斯顿维拉', goals: 11 }, avgGoals: 2.38, attendance: '2.7万' },
      { year: '2022-23', champion: '西汉姆联', runnerUp: '佛罗伦萨', topScorer: { name: '安东尼奥', team: '西汉姆联', goals: 9 }, avgGoals: 2.35, attendance: '2.6万' },
      { year: '2021-22', champion: '罗马', runnerUp: '费耶诺德', topScorer: { name: '佩德罗', team: '罗马', goals: 8 }, avgGoals: 2.32, attendance: '2.1万' },
    ],
    currentStandings: [],
    teamsList: [
      { name: '罗马', founded: '1927年', stadium: '奥林匹克球场', capacity: 70634, coach: '穆里尼奥' },
      { name: '西汉姆联', founded: '1895年', stadium: '伦敦体育场', capacity: 60000, coach: '莫耶斯' },
      { name: '佛罗伦萨', founded: '1926年', stadium: '弗兰基球场', capacity: 43147, coach: '伊塔利亚诺' },
    ],
    rules: '欧协联共有32支球队进入小组赛阶段，分为8个小组，每组4支球队进行双循环比赛。小组第一和三个成绩最好的小组第二晋级淘汰赛阶段。淘汰赛采用主客场两回合制，决赛为单场决胜。',
  },
  '足总杯': {
    name: '英格兰足总杯',
    country: '英格兰',
    founded: '1871年',
    teams: 64,
    description: '英格兰足总杯是世界上最古老的足球杯赛，成立于1871年。足总杯面向英格兰各级别联赛的俱乐部开放，是英格兰足球最重要的杯赛之一。',
    format: '64支球队单场淘汰赛，共8轮比赛',
    seasons: [
      { year: '2024-25', champion: '曼城', runnerUp: '曼联', topScorer: { name: '哈兰德', team: '曼城', goals: 9 }, avgGoals: 2.85, attendance: '4.5万' },
      { year: '2023-24', champion: '曼城', runnerUp: '曼联', topScorer: { name: '哈兰德', team: '曼城', goals: 8 }, avgGoals: 2.80, attendance: '4.4万' },
      { year: '2022-23', champion: '曼城', runnerUp: '曼联', topScorer: { name: '马赫雷斯', team: '曼城', goals: 6 }, avgGoals: 2.75, attendance: '4.3万' },
      { year: '2021-22', champion: '利物浦', runnerUp: '切尔西', topScorer: { name: '萨拉赫', team: '利物浦', goals: 5 }, avgGoals: 2.72, attendance: '3.5万' },
      { year: '2020-21', champion: '莱斯特城', runnerUp: '切尔西', topScorer: { name: '伊希纳乔', team: '莱斯特城', goals: 4 }, avgGoals: 2.68, attendance: '0.6万' },
      { year: '2019-20', champion: '阿森纳', runnerUp: '切尔西', topScorer: { name: '奥巴梅扬', team: '阿森纳', goals: 6 }, avgGoals: 2.75, attendance: '0.5万' },
      { year: '2018-19', champion: '曼城', runnerUp: '沃特福德', topScorer: { name: '阿圭罗', team: '曼城', goals: 5 }, avgGoals: 2.82, attendance: '5.2万' },
      { year: '2017-18', champion: '切尔西', runnerUp: '曼联', topScorer: { name: '阿扎尔', team: '切尔西', goals: 6 }, avgGoals: 2.78, attendance: '5.1万' },
      { year: '2016-17', champion: '阿森纳', runnerUp: '切尔西', topScorer: { name: '桑切斯', team: '阿森纳', goals: 5 }, avgGoals: 2.68, attendance: '5.0万' },
      { year: '2015-16', champion: '曼联', runnerUp: '水晶宫', topScorer: { name: '马夏尔', team: '曼联', goals: 4 }, avgGoals: 2.62, attendance: '4.9万' },
    ],
    currentStandings: [],
    teamsList: [],
    rules: '足总杯采用单场淘汰制，共分为八轮。前两轮为资格赛，第三轮到第六轮为主客场抽签决定，半决赛在温布利球场进行，决赛也在温布利球场举行。冠军获得下赛季欧联杯资格。',
  },
  '国王杯': {
    name: '西班牙国王杯',
    country: '西班牙',
    founded: '1902年',
    teams: 82,
    description: '西班牙国王杯是西班牙足球最重要的杯赛之一，成立于1902年。国王杯面向西班牙各级别联赛的俱乐部开放，是西班牙足球传统赛事。',
    format: '82支球队单场淘汰赛，低级别球队享有主场优势',
    seasons: [
      { year: '2024-25', champion: '巴塞罗那', runnerUp: '皇家马德里', topScorer: { name: '莱万多夫斯基', team: '巴塞罗那', goals: 8 }, avgGoals: 2.65, attendance: '3.2万' },
      { year: '2023-24', champion: '巴塞罗那', runnerUp: '毕尔巴鄂竞技', topScorer: { name: '拉菲尼亚', team: '巴塞罗那', goals: 7 }, avgGoals: 2.62, attendance: '3.1万' },
      { year: '2022-23', champion: '巴塞罗那', runnerUp: '皇家马德里', topScorer: { name: '莱万多夫斯基', team: '巴塞罗那', goals: 6 }, avgGoals: 2.58, attendance: '3.0万' },
      { year: '2021-22', champion: '皇家贝蒂斯', runnerUp: '瓦伦西亚', topScorer: { name: '伊格莱西亚斯', team: '贝蒂斯', goals: 5 }, avgGoals: 2.52, attendance: '2.2万' },
      { year: '2020-21', champion: '巴塞罗那', runnerUp: '毕尔巴鄂竞技', topScorer: { name: '梅西', team: '巴塞罗那', goals: 5 }, avgGoals: 2.48, attendance: '0.8万' },
      { year: '2019-20', champion: '皇家社会', runnerUp: '毕尔巴鄂竞技', topScorer: { name: '奥亚萨瓦尔', team: '皇家社会', goals: 4 }, avgGoals: 2.55, attendance: '0.6万' },
      { year: '2018-19', champion: '瓦伦西亚', runnerUp: '巴塞罗那', topScorer: { name: '罗德里戈', team: '瓦伦西亚', goals: 5 }, avgGoals: 2.62, attendance: '3.5万' },
      { year: '2017-18', champion: '巴塞罗那', runnerUp: '塞维利亚', topScorer: { name: '梅西', team: '巴塞罗那', goals: 6 }, avgGoals: 2.68, attendance: '3.4万' },
      { year: '2016-17', champion: '巴塞罗那', runnerUp: '阿拉维斯', topScorer: { name: '梅西', team: '巴塞罗那', goals: 5 }, avgGoals: 2.58, attendance: '3.3万' },
      { year: '2015-16', champion: '巴塞罗那', runnerUp: '塞维利亚', topScorer: { name: '苏亚雷斯', team: '巴塞罗那', goals: 7 }, avgGoals: 2.65, attendance: '3.2万' },
    ],
    currentStandings: [],
    teamsList: [],
    rules: '国王杯采用单场淘汰制，低级别球队享有主场优势。半决赛为两回合制，决赛为单场决胜。冠军获得下赛季欧联杯资格。',
  },
  '德国杯': {
    name: '德国杯',
    country: '德国',
    founded: '1952年',
    teams: 64,
    description: '德国杯是德国足球最重要的杯赛，成立于1952年。德国杯面向德国各级别联赛的俱乐部开放，是德国足球传统赛事。',
    format: '64支球队单场淘汰赛，低级别球队享有主场优势',
    seasons: [
      { year: '2024-25', champion: '勒沃库森', runnerUp: '拜仁慕尼黑', topScorer: { name: '维尔茨', team: '勒沃库森', goals: 7 }, avgGoals: 2.75, attendance: '3.8万' },
      { year: '2023-24', champion: '勒沃库森', runnerUp: 'RB莱比锡', topScorer: { name: '希克', team: '勒沃库森', goals: 6 }, avgGoals: 2.72, attendance: '3.7万' },
      { year: '2022-23', champion: 'RB莱比锡', runnerUp: '法兰克福', topScorer: { name: '恩昆库', team: 'RB莱比锡', goals: 5 }, avgGoals: 2.68, attendance: '3.6万' },
      { year: '2021-22', champion: 'RB莱比锡', runnerUp: '弗赖堡', topScorer: { name: '恩昆库', team: 'RB莱比锡', goals: 6 }, avgGoals: 2.65, attendance: '2.8万' },
      { year: '2020-21', champion: '多特蒙德', runnerUp: '莱比锡', topScorer: { name: '哈兰德', team: '多特蒙德', goals: 5 }, avgGoals: 2.62, attendance: '0.7万' },
      { year: '2019-20', champion: '拜仁慕尼黑', runnerUp: '勒沃库森', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 6 }, avgGoals: 2.75, attendance: '0.5万' },
      { year: '2018-19', champion: '拜仁慕尼黑', runnerUp: '莱比锡', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 5 }, avgGoals: 2.82, attendance: '4.2万' },
      { year: '2017-18', champion: '法兰克福', runnerUp: '拜仁慕尼黑', topScorer: { name: '阿莱', team: '法兰克福', goals: 6 }, avgGoals: 2.78, attendance: '4.1万' },
      { year: '2016-17', champion: '多特蒙德', runnerUp: '法兰克福', topScorer: { name: '奥巴梅扬', team: '多特蒙德', goals: 7 }, avgGoals: 2.72, attendance: '4.0万' },
      { year: '2015-16', champion: '拜仁慕尼黑', runnerUp: '多特蒙德', topScorer: { name: '莱万多夫斯基', team: '拜仁慕尼黑', goals: 5 }, avgGoals: 2.68, attendance: '3.9万' },
    ],
    currentStandings: [],
    teamsList: [],
    rules: '德国杯采用单场淘汰制，低级别球队享有主场优势。决赛在柏林奥林匹克球场举行。冠军获得下赛季欧联杯资格。',
  },
  '意大利杯': {
    name: '意大利杯',
    country: '意大利',
    founded: '1922年',
    teams: 44,
    description: '意大利杯是意大利足球最重要的杯赛，成立于1922年。意大利杯面向意大利各级别联赛的俱乐部开放，是意大利足球传统赛事。',
    format: '44支球队单场淘汰赛，部分轮次为两回合制',
    seasons: [
      { year: '2024-25', champion: '国际米兰', runnerUp: '罗马', topScorer: { name: '劳塔罗', team: '国际米兰', goals: 8 }, avgGoals: 2.55, attendance: '3.0万' },
      { year: '2023-24', champion: '国际米兰', runnerUp: '佛罗伦萨', topScorer: { name: '劳塔罗', team: '国际米兰', goals: 7 }, avgGoals: 2.52, attendance: '2.9万' },
      { year: '2022-23', champion: '国际米兰', runnerUp: '佛罗伦萨', topScorer: { name: '哲科', team: '国际米兰', goals: 6 }, avgGoals: 2.48, attendance: '2.8万' },
      { year: '2021-22', champion: '佛罗伦萨', runnerUp: '尤文图斯', topScorer: { name: '弗拉霍维奇', team: '尤文图斯', goals: 5 }, avgGoals: 2.45, attendance: '2.2万' },
      { year: '2020-21', champion: '那不勒斯', runnerUp: '尤文图斯', topScorer: { name: '因西涅', team: '那不勒斯', goals: 4 }, avgGoals: 2.42, attendance: '0.6万' },
      { year: '2019-20', champion: '那不勒斯', runnerUp: '尤文图斯', topScorer: { name: '默滕斯', team: '那不勒斯', goals: 5 }, avgGoals: 2.48, attendance: '0.5万' },
      { year: '2018-19', champion: '拉齐奥', runnerUp: '亚特兰大', topScorer: { name: '因莫比莱', team: '拉齐奥', goals: 6 }, avgGoals: 2.55, attendance: '3.5万' },
      { year: '2017-18', champion: '尤文图斯', runnerUp: 'AC米兰', topScorer: { name: '伊瓜因', team: '尤文图斯', goals: 5 }, avgGoals: 2.52, attendance: '3.4万' },
      { year: '2016-17', champion: '尤文图斯', runnerUp: '拉齐奥', topScorer: { name: '迪巴拉', team: '尤文图斯', goals: 4 }, avgGoals: 2.48, attendance: '3.3万' },
      { year: '2015-16', champion: '尤文图斯', runnerUp: 'AC米兰', topScorer: { name: '伊瓜因', team: '那不勒斯', goals: 6 }, avgGoals: 2.45, attendance: '3.2万' },
    ],
    currentStandings: [],
    teamsList: [],
    rules: '意大利杯采用单场淘汰制，部分轮次为两回合制。决赛在罗马奥林匹克球场举行。冠军获得下赛季欧联杯资格。',
  },
};

export default function LeaguePage({ params }: { params: { name: string } }) {
  const leagueNames: Record<string, string> = {
    '英超': '英超', '西甲': '西甲', '意甲': '意甲', '德甲': '德甲', '法甲': '法甲',
    '欧冠': '欧冠', '欧罗巴': '欧罗巴', '欧协联': '欧协联', '足总杯': '足总杯',
    '国王杯': '国王杯', '德国杯': '德国杯', '意大利杯': '意大利杯',
  };

  const normalizedName = leagueNames[params.name] || params.name;
  const league = leagueData[normalizedName] || {
    name: params.name, country: '未知', founded: '未知', teams: 0, description: '暂无详细信息',
    seasons: [], currentStandings: [], teamsList: [], rules: '', format: '',
  };

  return <LeagueContent league={league} />;
}